
alias_table = {
    "Sodium Benzoate": ["Sodium Benzote", "Sodium Benzoat", "Sodium Benazote", "E211"],
    "Sodium Nitrite": ["Sodium Nitirite", "Sodium Nitrate", "Nitrous Acid Sodium Salt"],
    "Sodium Nitrate": ["Sodium Nitrat", "Sodium Nitrade", "Chile Saltpeter"],
    "Sulfur Dioxide": ["Sulfer Dioxide", "Sulphur Dioxide (ellow Five", "Yellow-5", "TBritish spelling)", "E220"],
    "BHT": ["Butylated Hydroxy Toluene", "Butyl Hydroxy Toluene", "E321"],
    "Potassium Sorbate": ["Potasium Sorbate", "Potassium Sorbat", "E202"],
    "Sodium Erythorbate": ["Sodium Erythorobate", "Sodium Erythrobate", "E316"],
    "Propyl Paraben": ["Propyl Parabin", "Propyl Parabene", "E216"],
    "Propionic Acid": ["Proponic Acid", "Propanoic Acid", "E280"],
    "TBHQ": ["TBHQE", "Tert Butyl Hydroquinone", "E319"],
    "Nisin": ["Nisson", "Nysin", "E234"],
    "Red 40": ["Red Forty", "Red-40", "Allura Red AC", "E129"],
    "Yellow 5": ["Yellow Five", "Yellow-5", "Tartrazine", "E102"],
    "Tartrazine": ["Tartrazin", "Tartrazene", "E102"],
    "Blue 1 and 2": ["Blue One and Two", "Blu 1 & 2", "Brilliant Blue (E133)", "Indigotine (E132)"],
    "Aspartame": ["Aspirtame", "Aspartime", "E951"],
    "Sucralose": ["Sucralos", "Sucralase", "Splenda"],
    "Saccharin": ["Sacharin", "Saccharine", "Sweet'n Low", "E954"],
    "Acesulfame K": ["Ace-K", "Acesulfeme K", "Sunett", "E950"],
    "Polysorbate 80": ["Polysorbate Eighty", "Poly Sorbate 80", "Tween 80"],
    "Carboxymethylcellulose": ["Carboxy Methyl Cellulose", "Carboxy Methylcellulose", "CMC", "E466"],
    "Monosodium Glutamate": ["Mono Sodium Glutamate", "Monosodium Glutomate", "MSG"],
    "Hydrolyzed Vegetable Protein": ["Hydrolized Vegetable Protein", "Hydro Vegetal Protein", "HVP"],
    "Carrageenan": ["Carrageenan", "Carrageenin", "E407"],
    "Xanthan Gum": ["Zantham Gum", "Xantham Gum", "E415"],
    "Guar Gum": ["Gaur Gum", "Guar Gumme", "E412"],
    "Agar-Agar": ["Agar Agar", "Aggar-Aggar", "E406"],
    "Vitamin C": ["Ascorbic Acid", "Ascorbin Acid", "E300"],
    "Vitamin E": ["Tocopherol", "Alpha-Tocoferol", "E307"],
    "Citric Acid": ["Citiric Acid", "Citruc Acid", "E330"],
    "Lactic Acid": ["Lactic Asid", "Lactick Acid", "E270"],
    "Phosphoric Acid": ["Phosphoric Asid", "Phosphorik Acid", "E338"],
    "Malic Acid": ["Malick Acid", "Malik Acid", "E296"],
    "Monosodium Glutamate": ["Mono Sodium Glutamate", "Monosodium Glutomate", "MSG", "E621"],
    "MSG": ["Monosodium Glutamate", "Mono Sodium Glutamate", "E621"],
    "Disodium Inosinate": ["Di Sodium Inosinate", "Disodium Inosinatte", "E631"],
    "Hydrolyzed Vegetable Protein": ["Hydrolized Vegetable Protein", "Hydro Vegetal Protein", "HVP"],
    "Glycerol": ["Glycerin", "Glicerol", "E422"],
    "Propylene Glycol": ["Propylene Glycolle", "Propylen Glycol", "E1520"],
    "Sorbitol": ["Sorbitall", "Sorbitolol", "E420"],
    "Vanillin": ["Vanilline", "Vaniline", "Synthetic Vanilla"],
    "Ethyl Maltol": ["Etheyl Maltol", "E637"],
    "Oats": ["Oates", "Avena"],
    "Flaxseeds": ["Flax Seeds", "Linseeds"],
    "Chia Seeds": ["Chia", "Chia Grains"],
    "Almonds": ["Almond", "Amandes"],
    "Avocado": ["Avocato", "Avocad"],
    "Garlic": ["Garlick", "Ail"],
    "Olive Oil": ["Olive Oilve", "Oliv Oil"],
    "Berries": ["Berry Fruits", "Berry"],
    "Turmeric": ["Tumeric", "Curcuma"],
    "Green Tea": ["Grean Tea", "Matcha"],
    "Ginger": ["Gingerr", "Zingiber"],
    "Yogurt": ["Yoghurt", "Yogourt", "Curd"],
    "Kimchi": ["Kimchee", "Fermented Vegetables"],
    "Lentils": ["Lentle", "Lenthil", "Dal"],
    "Coconut Oil": ["Cocunut Oil", "Coco Oil"],
    "Pomegranates": ["Pomegranate", "Pomogranate", "Anar"],
    "Beans": ["Bean", "Legumes"],
    "Apples": ["Apple", "Malus"],
    "Carrots": ["Carrot", "Daucus"],
    "Kale": ["Keil", "Leaf Cabbage"],
    "High Fructose Corn Syrup": ["HFCS", "High-Fructose Corn Syrup", "Corn Sugar"],
    "Trans Fats": ["Transfat", "Trans Fatty Acids"],
    "Artificial Sweeteners": ["Artificial Sugar", "Fake Sweeteners", "Non-Nutritive Sweeteners"],
    "Monosodium Glutamate": ["MSG", "Mono Sodium Glutamate", "E621"],
    "Sodium": ["Salt", "Na", "Sodum"],
    "Artificial Colors": ["Synthetic Colors", "Food Dyes", "Artificial Colouring"],
    "Butylated HydroxyToluene": ["BHT", "Butyl Hydroxy Toluene", "E321"],
    "Sodium Nitrite": ["Sodium Nitrate", "Nitrite Salt", "E250"],
    "Propylene Glycol": ["Propylen Glycol", "PG", "E1520"],
    "Partially Hydrogenated Oils": ["Hydrogenated Oils", "Trans Oils"],
    "Mangoes": ["Mango", "Mangga", "Aam"],
    "Tomatoes": ["Tomato", "Tomoto", "Lycopersicon"],
    "Cinnamon": ["Cinnamom", "Cassia", "Dalchini"],
    "Psyllium Husk": ["Psyllium", "Isabgol", "Plantago"],
    "Pumpkin Seeds": ["Pumpkin Kernels", "Pepitas", "Pumpkin Nuts"],
    "Hemp Seeds": ["Hempseed", "Hemp Kernels", "Shelled Hemp"],
    "Beets": ["Beetroot", "Beet", "Beta Vulgaris"],
    "Cabbage": ["Cabage", "Leafy Cabbage", "Brassica"],
    "Broccoli": ["Brocoli", "Broccolini", "Brassica Oleracea"],
    "Fermented Soy": ["Soy Ferment", "Fermented Soya"],
    "Seaweed": ["Kelp", "Nori", "Marine Algae"],
    "Cocoa": ["Cacao", "Chocolate Powder", "Theobroma"],
    "Lemon": ["Lemon Citrus", "Citrus Limon", "Limon"],
    "Artichokes": ["Artichoke", "Cynara", "Globe Artichoke"],
    "Pineapple": ["Pine Apple", "Ananas", "Tropical Fruit"],
    "Coconut Water": ["Coconut Juice", "Coco Water"],
    "Walnuts": ["Walnut", "Juglans", "Shelled Walnuts"],
    "Mango": ["Mangga", "Mangifera", "Tropical Mango"],
    "Hemp Oil": ["Hempseed Oil", "Cannabis Oil"],
    "Pumpkin": ["Pumpkins", "Cucurbita", "Squash"],
    "Dipotassium Phosphate": ["Di Potassium Phosphate", "DKP", "E340"],
    "Sodium Benzoate": ["Sodium Benzote", "Sodium Benzoat", "E211"],
    "Polysorbate 80": ["Poly Sorbate 80", "Tween 80", "E433"],
    "BHA": ["Butylated Hydroxyanisole", "E320"],
    "Tert-Butylhydroquinone": ["TBHQ", "E319"],
    "Artificial Food Dyes": ["Synthetic Food Coloring", "Artificial Colorants"],
    "Phosphoric Acid": ["Phosphorik Acid", "Phosphorik", "E338"],
    "Maltodextrin": ["Malto Dextrin", "Modified Starch"],
    "Cornstarch": ["Corn Starch", "Maize Starch"],
    "Artificial Flavorings": ["Artificial Flavors", "Synthetic Flavoring"],
    "Olives": ["Olive", "Olea"],
    "Tart Cherries": ["Sour Cherries", "Prunus Cerasus"],
    "Kiwi": ["Kiwifruit", "Actinidia"],
    "Brussels Sprouts": ["Brussel Sprouts", "Mini Cabbages"],
    "Garbanzo Beans": ["Chickpeas", "Cicer Arietinum"],
    "Peas": ["Green Peas", "Pisum Sativum"],
    "Quinoa": ["Quinua", "Chenopodium"],
    "Acai Berries": ["Acai", "Euterpe Oleracea"],
    "Papaya": ["Pawpaw", "Carica Papaya"],
    "Trans Fats": ["Trans Fatty Acids", "Partially Hydrogenated Oils"],
    "High-Fructose Corn Syrup": ["HFCS", "Corn Syrup"],
    "Artificial Sweeteners": ["Non-Nutritive Sweeteners", "Sugar Substitutes"],
    "Refined Sugar": ["White Sugar", "Processed Sugar"],
    "Excess Salt": ["Too Much Sodium", "High Sodium"],
    "Emulsifiers": ["Emulsifying Agents", "Food Stabilizers"],
    "Artificial Colors": ["Synthetic Dyes", "Artificial Colouring"],
    "Preservatives": ["Preservative Agents", "Additives"],
    "Monosodium Glutamate (MSG)": ["MSG", "Mono Sodium Glutamate", "E621"],
    "Tartrazine": ["Yellow 5", "E102"],
    "Sodium Nitrite": ["Nitrite Salt", "E250"],
    "Olestra": ["Fat Substitute", "Synthetic Fat"],
    "Brominated Vegetable Oil": ["BVO", "Brominated Oil"],
    "Potassium Bromate": ["Potassium Bromide", "E924"],
    "Acesulfame Potassium": ["Ace-K", "E950"],
    "Glyphosate": ["Weed Killer", "Roundup Chemical"],
    "Propylparaben": ["Propyl Paraben", "E216"],
    "High-Fructose Corn Syrup (HFCS)": ["Corn Syrup", "HFCS"],
    "Artificial Trans Fats": ["Synthetic Trans Fats", "Hydrogenated Trans Fats"],
    "Refined Grains": ["White Grains", "Processed Grains"],
    "Sodium Nitrate/Nitrite": ["Nitrate and Nitrite", "E251/E250"],
    "Carrageenan": ["E407", "Seaweed Extract"],
    "Artificial Sweeteners (Aspartame, Sucralose)": ["Aspartame and Sucralose", "Non-Sugar Sweeteners"],
    "Palm Oil": ["Palma Oil", "Elaeis Guineensis Oil"],
    "Xanthan Gum": ["E415", "Thickening Agent"],
    "Titanium Dioxide": ["TiO2", "Food Whitening Agent"],
    "Hydrogenated Oils": ["Trans Oils", "Processed Fats"],
    "Artificial Food Coloring": ["Synthetic Food Colors", "Artificial Dyes"],
    "Sodium Benzoate": ["Sodium Benzote", "E211"],
    "Soy Lecithin": ["Lecithin", "Soy-Based Emulsifier"],
    "Phosphoric Acid": ["E338", "Acidifying Agent"],
    "Maltodextrin": ["Modified Starch", "E1400"],
    "Butylated Hydroxyanisole (BHA)": ["BHA", "E320"],
    "Propylene Glycol": ["PG", "E1520"],
    "Sodium Phosphate": ["Phosphate Salt", "E339"],
    "Acesulfame Potassium (Ace-K)": ["Ace K", "E950"],
    "Inulin": ["Prebiotic Fiber", "Chicory Root Fiber"],
    "Guar Gum": ["E412", "Thickening Agent"],
    "Calcium Propionate": ["E282", "Antimicrobial Agent"],
    "Steviol Glycosides (Stevia)": ["Stevia", "E960"],
    "Soy Protein Isolate": ["Soy Protein", "SPI", "Isolated Soy Protein"],
    "Aspartic Acid": ["Aspartate", "E264"],
    "Citric Acid": ["Citrate", "E330", "Sour Salt"],
    "Modified Corn Starch": ["Corn Starch", "Modified Starch"],
    "Malted Barley Flour": ["Barley Malt Flour", "Malt Flour"],
    "Sodium Caseinate": ["Casein", "Milk Protein"],
    "Tertiary Butylhydroquinone (TBHQ)": ["TBHQ", "E319"],
    "Erythritol": ["Sugar Alcohol", "E968"],
    "Agar-Agar": ["Agar", "E406", "Kanten"],
    "Beta-Carotene": ["Carotene", "Provitamin A", "E160a"],
    "Carboxymethyl Cellulose": ["CMC", "Cellulose Gum", "E466"],
    "Fumaric Acid": ["Fumarate", "E297"],
    "Calcium Stearate": ["E572", "Stearic Acid Calcium Salt"],
    "Propyl Gallate": ["PG", "E310"],
    "Lactic Acid": ["Lactate", "E270"],
    "Gum Arabic": ["Acacia Gum", "E414"],
    "Sodium Lactate": ["Lactate Salt", "E325"],
    "Gellan Gum": ["Gellen Gum", "E418"],
    "Isomalt": ["Isomaltitol", "E953"],
    "Potassium Sorbate": ["Sorbic Acid Salt", "E202"],
    "Riboflavin": ["Vitamin B2", "E101"],
    "Tapioca Starch": ["Cassava Starch", "Tapioca Flour"],
    "Tricalcium Phosphate": ["TCP", "E341"],
    "Confectioner's Glaze": ["Shellac", "Pharmaceutical Glaze"],
    "Dextrose": ["Glucose", "Corn Sugar"],
    "Psyllium Husk": ["Plantago Husk", "Isabgol"],
    "Polydextrose": ["Synthetic Fiber", "E1200"],
    "Pectin": ["Fruit Pectin", "E440"],
    "Malt Extract": ["Malted Barley Extract", "Malt Syrup"],
    "Sucralose": ["Splenda", "E955"],
    "Glucomannan": ["Konjac Powder", "Dietary Fiber"],
    "Calcium Sulfate": ["Gypsum", "E516"],
    "Fructooligosaccharides (FOS)": ["FOS", "Prebiotic Fiber"],
    "Maltose": ["Malt Sugar", "Disaccharide"],
    "Sodium Bicarbonate": ["Baking Soda", "E500"],
    "High Oleic Sunflower Oil": ["HO Sunflower Oil", "Sunflower Seed Oil"],
    "Carrageenan": ["Seaweed Extract", "E407"],
    "Xylitol": ["Sugar Substitute", "E967"],
    "Ascorbic Acid": ["Vitamin C", "E300"],
    "Artificial Flavoring": ["Synthetic Flavors", "Food Flavoring"],
    "Hydrolyzed Vegetable Protein": ["HVP", "Vegetable Protein Hydrolysate"],
    "Palm Oil": ["Palm Kernel Oil", "Elaeis Guineensis Oil"],
    "MCT Oil": ["Medium-Chain Triglyceride Oil", "Coconut Oil Derivative"],
    "Calcium Carbonate": ["Limestone", "E170", "CaCO3"],
    "Rice Bran Oil": ["RBO", "Rice Oil"],
    "Spirulina": ["Blue-Green Algae", "Arthrospira"],
    "Calcium Citrate": ["E333", "Citrate of Lime"],
    "Agar-Agar": ["Agar", "E406", "Kanten"],
    "Sodium Acid Pyrophosphate": ["SAPP", "E450"],
    "Potassium Citrate": ["Tripotassium Citrate", "E332"],
    "Tapioca Maltodextrin": ["Tapioca Starch Derivative", "Modified Tapioca Starch"],
    "Erythritol": ["Sugar Alcohol", "E968"],
    "Yeast Extract": ["Autolyzed Yeast", "Baker's Yeast Extract"],
    "Rice Flour": ["Ground Rice", "Rice Powder"],
    "Monoglycerides and Diglycerides": ["Emulsifiers", "E471"],
    "Citric Acid": ["Citrate", "E330", "Sour Salt"],
    "Sorbitol": ["E420", "Sugar Alcohol"],
    "Silicon Dioxide": ["SiO2", "E551"],
    "Guarana Extract": ["Paullinia Cupana", "Guarana Seed Extract"],
    "Modified Starch": ["E1404", "Altered Starch"],
    "Casein": ["Milk Protein", "Cheese Protein"],
    "Calcium Chloride": ["E509", "CaCl2"],
    "Carob Gum": ["Locust Bean Gum", "E410"],
    "Pectin": ["Fruit Pectin", "E440"],
    "Beta-Carotene": ["Carotene", "Provitamin A", "E160a"],
    "Sodium Nitrite": ["NaNO2", "E250"],
    "Turmeric Extract": ["Curcumin", "Turmeric Powder"],
    "Methylcellulose": ["MC", "Hydroxypropyl Methylcellulose"],
    "Inulin": ["Chicory Root Fiber", "Prebiotic Fiber"],
    "Sucrose": ["Table Sugar", "Cane Sugar"],
    "Stevia": ["Steviol Glycosides", "Rebiana"],
    "Cellulose Gum": ["Carboxymethylcellulose", "E466"],
    "L-Taurine": ["Taurine", "2-Aminoethanesulfonic Acid"],
    "Golden Rice": ["Vitamin A Rice", "Biofortified Rice"],
    "Bt Corn": ["Bacillus Thuringiensis Corn", "GM Corn"],
    "Omega-3 Canola": ["Canola Oil with Omega-3", "Modified Canola Oil"],
    "High-Oleic Soybean Oil": ["HOSO", "Soybean Oil"],
    "Water": ["H2O"],
    "Sugar": ["Sucrose", "Table Sugar"],
    "Salt": ["Sodium Chloride", "Table Salt"],
    "Corn syrup": ["Glucose Syrup"],
    "High fructose corn syrup": ["HFCS", "Corn Sugar"],
    "Honey": ["Bee Honey"],
    "Maple syrup": ["Maple Sugar Syrup"],
    "Molasses": ["Treacle"],
    "Brown sugar": ["Soft Sugar"],
    "White sugar": ["Granulated Sugar"],
    "Powdered sugar": ["Confectioner's Sugar", "Icing Sugar"],
    "Agave syrup": ["Agave Nectar"],
    "Stevia": ["Stevia Extract"],
    "Artificial sweeteners": ["Sucralose", "Aspartame", "Saccharin"],  
    "Dextrose": ["Glucose"],
    "Sucrose": ["Table Sugar"],
    "Maltodextrin": ["MDX"],
    "Sorbitol": ["Glucitol"],
    "Mannitol": ["E421"],
    "Xylitol": ["Birch Sugar"],
    "Erythritol": ["Sugar Alcohol"],
    "Artificial flavoring": ["Artificial Flavors"],
    "Natural flavoring": ["Natural Extracts"],
    "Monosodium glutamate (MSG)": ["MSG", "E621"],
    "Citric acid": ["Sour Salt", "E330"],
    "Sodium benzoate": ["Sodium Benzote", "Sodium Benzoat", "Sodium Benazote", "E211"],
    "Potassium sorbate": ["E202"],
    "Ascorbic acid (Vitamin C)": ["Vitamin C", "E300"],
    "Vinegar": ["Acetic Acid", "White Vinegar", "Apple Cider Vinegar", "Balsamic Vinegar"],
    "Soybean oil": ["Soy Oil"],
    "Palm oil": ["Palm Kernel Oil"],
    "Canola oil": ["Rapeseed Oil"],
    "Olive oil": ["Extra Virgin Olive Oil"],
    "Sunflower oil": ["Sunflower Seed Oil"],
    "Vegetable oil": ["Plant-Based Oil"],
    "Coconut oil": ["Coconut Fat"],
    "Butter": ["Dairy Butter"],
    "Margarine": ["Butter Substitute"],
    "Lard": ["Pork Fat"],
    "Egg yolk": ["Egg Yellow"],
    "Whole eggs": ["Fresh Eggs"],
    "Egg whites": ["Egg Albumen"],
    "Milk": ["Whole Milk", "Cow Milk"],
    "Skim milk": ["Nonfat Milk"],
    "Evaporated milk": ["Condensed Milk without Sugar"],
    "Condensed milk": ["Sweetened Milk"],
    "Cream": ["Heavy Cream"],
    "Sour cream": ["Fermented Cream"],
    "Yogurt": ["Dahi", "Curd"],
    "Buttermilk": ["Cultured Milk"],
    "Cheese": ["Cottage Cheese", "Cream Cheese", "Mozzarella", "Parmesan", "Cheddar", "Gouda", "Swiss Cheese", "Ricotta", "Blue Cheese"],
    "Pectin": ["E440"],
    "Guar gum": ["Guaran"],
    "Xanthan gum": ["E415"],
    "Agar agar": ["Gelidium Extract"],
    "Gelatin": ["Collagen"],
    "Carrageenan": ["E407"],
    "Modified corn starch": ["Modified Starch"],
    "Potato starch": ["Potato Flour"],
    "Arrowroot powder": ["Arrowroot Starch"],
    "Tapioca starch": ["Tapioca Flour"],
    "Wheat flour": ["White Flour"],
    "All-purpose flour": ["AP Flour"],
    "Whole wheat flour": ["Whole Grain Flour"],
    "Cake flour": ["Soft Wheat Flour"],
    "Semolina flour": ["Durum Flour"],
    "Rye flour": ["Rye Meal"],
    "Cornmeal": ["Maize Meal"],
    "Rice flour": ["Ground Rice"],
    "Almond flour": ["Almond Meal"],
    "Coconut flour": ["Coconut Powder"],
    "Oat flour": ["Oat Meal"],
    "Buckwheat flour": ["Kasha Flour"],
    "Soy flour": ["Soybean Flour"],
    "Spelt flour": ["Ancient Grain Flour"],
    "Baking soda": ["Sodium Bicarbonate"],
    "Baking powder": ["Chemical Leavening Agent"],
    "Yeast": ["Active Dry Yeast"],
    "Flaxseed": ["Linseed"],
    "Chia seeds": ["Salvia Hispanica Seeds"],
    "Hemp seeds": ["Hemp Hearts"],
    "Sunflower seeds": ["Sunflower Kernels"],
    "Pumpkin seeds": ["Pepitas"],
    "Sesame seeds": ["Til"],
    "Almonds": ["Sweet Almond"],
    "Walnuts": ["Juglans"],
    "Cashews": ["Cashew Nut"],
    "Pecans": ["Pecan Nut"],
    "Brazil nuts": ["Brazilian Nut"],
    "Macadamia nuts": ["Queensland Nut"],
    "Hazelnuts": ["Filberts"],
    "Pine nuts": ["Pignoli"],
    "Peanuts": ["Groundnut"],
    "Nutmeg": ["Myristica"],
    "Cinnamon": ["Cassia"],
    "Cloves": ["Dried Buds"],
    "Ginger": ["Zingiber"],
    "Turmeric": ["Haldi"],
    "Garlic": ["Allium"],
    "Onion": ["Bulb Onion"],
    "Chives": ["Allium Schoenoprasum"],
    "Parsley": ["Flat Leaf Parsley"],
    "Basil": ["Ocimum"],
    "Oregano": ["Wild Marjoram"],
    "Thyme": ["Thymus"],
    "Rosemary": ["Rosmarinus"],
    "Dill": ["Anethum"],
    "Sage": ["Salvia"],
    "Bay leaves": ["Bay Laurel"],
    "Mint": ["Mentha"],
    "Cumin": ["Jeera"],
    "Paprika": ["Capsicum"],
    "Chili powder": ["Ground Chili"],
    "Cayenne pepper": ["Red Pepper"],
    "Black pepper": ["Peppercorn"],
    "High-Oleic Soybean Oil": ["HOSO", "Soybean Oil"]
}